sudo: required

language: python

python:
  - "3.6"

env: SCIDB_VER=18.1 SCIDB_IMG=18.1 ARROW_VER=0.8.0-2

services:
  - docker

before_install:
  - docker pull rvernica/scidb:${SCIDB_IMG}
  - docker run
    --name scidb
    --detach
    --publish 8080:8080
    --volume `pwd`:/accelerated_io_tools
    --env ARROW_VER=${ARROW_VER}
    rvernica/scidb:${SCIDB_IMG}
  - while ! curl http://localhost:8080/version; do sleep 5; done

install:
  - docker exec --tty scidb /accelerated_io_tools/tests/docker-install.sh

script:
  - docker exec --tty scidb /accelerated_io_tools/tests/test.sh
  - docker exec --tty scidb /accelerated_io_tools/tests/test_arrow.sh

after_failure:
  - docker exec --tty scidb cat /accelerated_io_tools/tests/test.out
  - docker exec --tty scidb cat /accelerated_io_tools/tests/test_arrow.out
  - docker logs scidb
