sudo: required

language: python

python:
  - "3.6"

env: SCIDB_VER=18.1 SCIDB_IMG=18.1 ARROW_VER=0.8.0-2

services:
  - docker

before_install:
  - mkdir shim
  - wget --no-verbose --output-document -
    https://github.com/Paradigm4/shim/archive/master.tar.gz
    | tar --extract --gzip --directory=shim
  - mkdir scidb-py
  - wget --no-verbose --output-document -
    https://github.com/Paradigm4/scidb-py/archive/master.tar.gz
    | tar --extract --gzip --directory=scidb-py
  - docker pull rvernica/scidb:${SCIDB_IMG}
  - docker run
    --name scidb
    --detach
    --publish 8080:8080
    --volume `pwd`:/accelerated_io_tools
    --env ARROW_VER=${ARROW_VER}
    rvernica/scidb:${SCIDB_IMG}
  - docker exec scidb ls /accelerated_io_tools/shim
  - docker exec scidb ls /accelerated_io_tools/scidb-py
  - while ! curl http://localhost:8080/version; do sleep 5; done

install:
  - docker exec --tty scidb /accelerated_io_tools/tests/docker-install.sh

script:
  - docker exec --tty scidb /accelerated_io_tools/tests/test.sh
  - docker exec --tty scidb /accelerated_io_tools/tests/test_arrow.sh

after_failure:
  - docker exec --tty scidb cat /accelerated_io_tools/tests/test.out
  - docker exec --tty scidb cat /accelerated_io_tools/tests/test_arrow.out
  - docker logs scidb
